examples/booking_app/lib/feature_hotel/search/ui_components/hotel_sort_page.dart
examples/booking_app/lib/feature_hotel/search/views/search_page.dart
examples/favorites_advanced/favorites_advanced_base/lib/src/common_ui_components/hotel_header.dart
examples/favorites_advanced/favorites_advanced_base/lib/src/common_ui_components/hotel_list_item.dart
examples/favorites_advanced/favorites_advanced_base/lib/src/repositories/hotels_repository.dart
examples/favorites_advanced/favorites_advanced_base/lib/src/utils/dialog_messages.dart

- dialog animation
- hotel list items
- yes/no dialog UI

UI polishment

---

examples/booking_app/pubspec.yaml
examples/favorites_advanced/rx_bloc_favorites_advanced/pubspec.yaml
packages/flutter_rx_bloc/doc/ui_integration_tests.md
packages/rx_bloc/README.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_generator/CHANGELOG.md
packages/rx_bloc_generator/lib/src/utilities/extensions.dart
packages/rx_bloc_generator/lib/src/utilities/utilities.dart
packages/rx_bloc_generator/pubspec.yaml
packages/rx_bloc_generator/test/generator_test.dart
packages/rx_bloc_list/example/pubspec.yaml
packages/rx_bloc_list/pubspec.yaml

Migrate to null-safety

---

examples/reminders/lib/feature_dashboard/views/dashboard_page.dart
examples/reminders/lib/l10n/arb/app_en.arb
examples/reminders/lib/l10n/arb/app_es.arb

Show a message in a snackbar for a deleted reminder and show another message for a created reminder.
The message is the same regardless of whether the reminders was added to dashboard or deleted from it.

Show a message in a snackbar for deleted and created reminders

---

examples/reminders/lib/feature_dashboard/views/dashboard_page.dart
examples/reminders/lib/feature_reminder_list/views/reminder_list_page.dart

Add SafeArea on DashboardPage and on ReminderListPage

Add safe are on DashboardPage and on ReminderListPage

---

examples/booking_app/ios/Runner.xcodeproj/project.pbxproj
examples/booking_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
examples/counter/ios/Flutter/AppFrameworkInfo.plist
examples/counter/ios/Runner.xcodeproj/project.pbxproj
examples/counter/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
examples/counter/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
examples/favorites_advanced/rx_bloc_favorites_advanced/ios/Runner.xcodeproj/project.pbxproj
examples/favorites_advanced/rx_bloc_favorites_advanced/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
examples/reminders/ios/Runner.xcodeproj/project.pbxproj
examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc.dart
examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc.rxb.g.dart
examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc_extensions.dart
examples/reminders/lib/feature_dashboard/views/dashboard_page.dart

Unify behaviour on both pages, so that when we make a pull to refresh on DashboardPage the loading indication is the same as in the ReminderListPage.

Unify behaviour on both pages

---

extensions/intellij/intellij_generator_plugin/build.gradle
extensions/intellij/intellij_generator_plugin/src/main/resources/templates/di/dependencies.dart.template
packages/rx_bloc/CHANGELOG.md
packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/app/build.gradle
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/app/src/main/AndroidManifest.xml
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/build.gradle

bump android settings, remove dependencies singleton

bump android settings, remove dependencies singleton

---

packages/flutter_rx_bloc/lib/src/rx_text_form_field_builder.dart
packages/rx_bloc_generator/lib/src/build_controller.dart
packages/rx_bloc_generator/pubspec.yaml
packages/rx_bloc_generator/test/src/rx_bloc_test.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_class_only.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_states_no_methods.dart

Due to some existing and unchanged tests failing (for an unknown reason) the pipeline broke. This PR contains code that should fix the pipeline.

Fix pipeline issues

---

packages/flutter_rx_bloc/lib/src/rx_text_form_field_builder.dart
packages/rx_bloc_list/CHANGELOG.md
packages/rx_bloc_list/pubspec.yaml

Update rx_bloc_list dependencies to use latest

---

examples/reminders/lib/feature_reminder_list/views/add_reminder_dialog.dart

Increase the lines for the error text of reminder title validation

Increase the lines for the error text of reminder title validation

---

packages/rx_bloc_list/CHANGELOG.md
packages/rx_bloc_list/README.md
packages/rx_bloc_list/lib/src/extensions/identifiable_extensions.dart

Add documentation in the Readme file for the withLatestFromIdentifiableList method

Add documentation for the withLatestFromIdentifiableList in README

---

examples/booking_app/android/build.gradle
examples/booking_app/android/gradle/wrapper/gradle-wrapper.properties
examples/booking_app/lib/base/ui_components/sorting_bar.dart
examples/booking_app/lib/feature_home/views/home_page.dart
examples/booking_app/lib/feature_hotel_search/views/hotel_search_page.dart
examples/counter/android/build.gradle
examples/counter/android/gradle/wrapper/gradle-wrapper.properties
examples/counter/lib/pages/home_page.dart
examples/favorites_advanced/rx_bloc_favorites_advanced/android/build.gradle
examples/favorites_advanced/rx_bloc_favorites_advanced/android/gradle/wrapper/gradle-wrapper.properties
examples/favorites_advanced/rx_bloc_favorites_advanced/lib/feature_home/views/home_page.dart
packages/rx_bloc_generator/lib/src/builders/event_arguments_class.dart
packages/rx_bloc_generator/lib/src/utilities/extensions.dart

Fixes for building with flutter 3.7.0

Fix/flutter 3.7.0

---

.github/workflows/flutter_rx_bloc_publish.yaml
.github/workflows/rx_bloc_generator_publish.yaml
.github/workflows/rx_bloc_list_publish.yaml
.github/workflows/rx_bloc_publish.yaml
.github/workflows/rx_bloc_test_publish.yaml
packages/flutter_rx_bloc/.pubignore
packages/flutter_rx_bloc/pubspec.yaml
packages/flutter_rx_bloc/pubspec_overrides.yaml
packages/rx_bloc_generator/.pubignore
packages/rx_bloc_generator/pubspec.yaml
packages/rx_bloc_generator/pubspec_overrides.yaml
packages/rx_bloc_list/.pubignore
packages/rx_bloc_list/pubspec.yaml
packages/rx_bloc_list/pubspec_overrides.yaml
packages/rx_bloc_test/.pubignore
packages/rx_bloc_test/pubspec.yaml
packages/rx_bloc_test/pubspec_overrides.yaml

Move dependency_overrides in separate files where applicable. Add .pubignore in packages that contains dependency_overrides.yaml. Add CD pipelines where missed
closes #457

Create CD pipelines

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_deeplink/__brick__/lib/feature_enter_message/views/enter_message_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_widget_toolkit/__brick__/lib/feature_widget_toolkit/di/widget_toolkit_with_dependencies.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_widget_toolkit/__brick__/lib/feature_widget_toolkit/repositories/search_repository.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_widget_toolkit/__brick__/lib/feature_widget_toolkit/services/custom_edit_address_service.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_widget_toolkit/__brick__/lib/feature_widget_toolkit/services/search_service.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_widget_toolkit/__brick__/lib/feature_widget_toolkit/views/edit_fields_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/router.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/routes/showcase_routes.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/arb/error/es.arb
packages/rx_bloc_cli/pubspec.yaml

Add EditAddressWidget example to the EditFieldsPage

Add EditAddressWidget example to the EditFieldsPage

---

packages/flutter_rx_bloc/example/pubspec.lock
packages/rx_bloc_generator/CHANGELOG.md
packages/rx_bloc_generator/pubspec.yaml
packages/rx_bloc_list/example/pubspec.lock

Update the dependencies of rx_bloc_generator to the newest versions

Update the dependencies to the newest versions

---

packages/rx_bloc_cli/bin/compile_win.bat
packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/pages/counter_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_realtime_communication/__brick__/lib/base/utils/sse_utilities.dart
packages/rx_bloc_cli/mason_templates/bricks/patrol_integration_tests/__brick__/integration_test/main/configuration/build_app.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/pages/login_page.dart

Fix hardcoded imports, fix app not compiling with sse enabled

---

packages/rx_bloc_cli/bin/compile.sh
packages/rx_bloc_cli/bin/compile_win.bat
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/build.gradle
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/data_sources/remote/interceptors/analytics_interceptor.dart

- Update google-services version in build.gradle
- Convert some parameters in analytics_interceptor to string
- Enable analytics in example project

Fix issues with analytics feature enabled

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

- Fix automated tests not running when analytics is enabled
- Fix android compilation issues

rx_bloc_cli fixes

---

packages/rx_bloc_cli/mason_templates/bricks/lib_dev_menu/__brick__/lib/lib_dev_menu/ui_components/app_dev_menu.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_dev_menu/__brick__/lib/lib_dev_menu/ui_components/dev_menu_bottom_sheet.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/app/{{project_name}}.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/data_sources/remote/http_clients/api_http_client.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/data_sources/remote/http_clients/plain_http_client.dart

- Fixed visual issues when keyboard pushes dev menu widget all way up from the screen 
- Fixed some code analysis issues

Keyboard pushing up dev menu widget fix

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

- Changelog description added
- Pubspec version increased

Version 2.7.0

---

packages/rx_bloc_cli/README.md
packages/rx_bloc_cli/mason_templates/README.md

Bricks documentation

---

packages/flutter_rx_bloc/CHANGELOG.md
packages/rx_bloc_generator/CHANGELOG.md
packages/rx_bloc_list/CHANGELOG.md
packages/rx_bloc_test/CHANGELOG.md

Update the dates into CHANGELOG.md files

Prepare for release

---

packages/rx_bloc_cli/lib/src/utils/git_ignore_creator.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth/__brick__/lib/lib_router/routes/onboarding_routes.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/router.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/routes/profile_routes.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/routes/routes.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/routes/showcase_routes.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/di/{{project_name}}_with_dependencies.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_home/views/home_page.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml

Update go_router and go_router builder versions

---

packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/models/pin_code_arguments.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/views/update_pin_page.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/pubspec.yaml

This PR should fix the biometrics button being displayed on the confirm PIN screen

Fix biometrics button showing on confirm pin screen

---

packages/rx_bloc_cli/mason_templates/README.md

Update steps for creating a brick

---

.github/PULL_REQUEST_TEMPLATE.md

Initial proposal for pull request template

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/README.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/pubspec.yaml

> Closes: #591 
Updates the version of `go_router` used in the generated project.
~~Manually tested against Acceptance Criteria~~
~~UI checked in Light / Dark mode~~
*Stability*
~~Added unit tests for new code and verified existing tests work as expected~~
*Code quality*
~~If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~~

Update go_router version to 11.x.x

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

> Closes: -
-
*Stability*
*Code quality*

Prepare release

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/repositories/push_notification_repository.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/steps_utils/{{#has_authentication}}profile_page_steps.dart{{/has_authentication}}

> Closes: #598 
~~UI checked in Light / Dark mode~~
*Stability*
~~Added unit tests for new code and verified existing tests work as expected~~
*Code quality*
~~If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~~

Log missing configuration errors, remove integration test step

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/repositories/push_notification_repository.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_profile/views/profile_page.dart

> Closes: #613 
*Stability*
~~Added unit tests for new code and verified existing tests work as expected~~
*Code quality*
~~If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~~

Remove app lifecycle states, fix bug related to notifications

---

examples/reminders/ios/Runner.xcodeproj/project.pbxproj
examples/reminders/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
examples/reminders/lib/base/app/config/app_config.dart
examples/reminders/lib/base/app/config/environment_config.dart
examples/reminders/lib/base/data_sources/remote/interceptors/analytics_interceptor.dart
examples/reminders/lib/base/data_sources/remote/reminders_data_source.dart
examples/reminders/lib/base/data_sources/remote/reminders_firebase_data_source.dart
examples/reminders/lib/base/repositories/firebase_repository.dart
examples/reminders/lib/base/repositories/reminders_repository.dart
examples/reminders/lib/base/services/firebase_service.dart
examples/reminders/lib/base/services/reminders_service.dart
examples/reminders/lib/base/theme/design_system.dart
examples/reminders/lib/base/theme/reminders_theme.dart
examples/reminders/lib/base/utils/validators/login_field_validators.dart
examples/reminders/lib/base/utils/validators/validators.dart

Add reminders documentation for the base directory and its subdirectories excluding common blocs and widgets

Add reminders documentation for the base directory and its subdirectories

---

examples/reminders/lib/base/common_blocs/coordinator_bloc.dart
examples/reminders/lib/base/common_blocs/coordinator_bloc_extensions.dart
examples/reminders/lib/base/common_blocs/firebase_bloc.dart
examples/reminders/lib/base/common_blocs/firebase_bloc_extensions.dart
examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc.dart
examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc_extensions.dart
examples/reminders/lib/feature_dashboard/di/dashboard_page_with_dependencies.dart
examples/reminders/lib/feature_dashboard/models/dashboard_model.dart
examples/reminders/lib/feature_dashboard/services/dashboard_service.dart
examples/reminders/lib/feature_reminder_list/di/reminder_list_page_with_dependencies.dart
examples/reminders/lib/feature_reminder_list/services/reminder_list_service.dart
examples/reminders/lib/feature_reminder_manage/blocs/reminder_manage_bloc.dart
examples/reminders/lib/feature_reminder_manage/blocs/reminder_manage_bloc_extensions.dart
examples/reminders/lib/feature_splash/blocs/splash_bloc.dart
examples/reminders/lib/feature_splash/di/splash_page_with_dependencies.dart
examples/reminders/lib/l10n/l10n.dart
examples/reminders/lib/lib_router/blocs/router_bloc.dart
examples/reminders/lib/lib_router/models/route_data_model.dart
examples/reminders/lib/lib_router/models/routes_path.dart
examples/reminders/lib/lib_router/router.dart
examples/reminders/lib/lib_router/routes/navigation_routes.dart
examples/reminders/lib/lib_router/routes/root/login_routes.dart
examples/reminders/lib/lib_router/routes/root/splash_routes.dart

Add documentation for reminders features excluding the views/widgets

Add documentation for reminders features

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml

Fixes a dependency issue in generated projects with rx_bloc_clli.

Remove alice override in generated projects

---

.github/workflows/build_and_test_rx_bloc_packages.yaml
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/pubspec.yaml

Fixes an issue where we weren't able to publish the package due to incorrect dependencies.

Update rx_bloc_cli dependencies

---

packages/rx_bloc_list/CHANGELOG.md
packages/rx_bloc_list/lib/src/models/paginated_list.dart
packages/rx_bloc_list/lib/src/widgets/rx_paginated_builder.dart
packages/rx_bloc_list/pubspec.yaml
packages/rx_bloc_list/test/paginated_list_test.dart

Fix paginated list scroll events

---

packages/rx_bloc/CHANGELOG.md
packages/rx_bloc/pubspec.yaml

Lower the meta requirement from ^1.11.0 to ^1.10.0
*Stability*
*Code quality*

Lower the meta requirement from ^1.11.0 to ^1.10.0

---

packages/rx_bloc_list/CHANGELOG.md
packages/rx_bloc_list/lib/src/widgets/rx_paginated_builder.dart
packages/rx_bloc_list/pubspec.yaml

Fix the RxPaginatedBuilder `bloc` parameter
*Stability*
*Code quality*

Fix the RxPaginatedBuilder `bloc` parameter

---

packages/rx_bloc_cli/lib/src/processors/android/app_build_gradle_processor.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/lib_translations/data_sources/translations_remote_data_source.g.dart
packages/rx_bloc_generator/lib/src/utilities/event_args_record.dart
packages/rx_bloc_generator/lib/src/utilities/extensions.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_class_only.dart

Fixes to pana score of rx_bloc packages

Fix pana score of rx_bloc_generator

---

packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/docs/continuous_delivery.md
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_codemagic}}codemagic.yaml{{/cicd_codemagic}}

> Closes: #706 
Addresses leftover comments from testing of the Codemagic functionality
*Stability*
~- [ ] Checked if changes affect any features and verified affected features work as expected~
*Code quality*
~- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`~
~- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~

Update codemagic workflow inputs and documentation

---

.github/workflows/golden_test_generation.yaml

Add todoapp in goldens generation workflow 
*Stability*
*Code quality*

Add todo to golden generation workflow

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/docs/continuous_delivery.md
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/build_and_deploy_app.yaml
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/fastlane_android_custom_build_and_deploy.yaml
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/fastlane_ios_custom_build_and_deploy.yaml
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/run_app_tests.yaml
packages/rx_bloc_cli/pubspec.yaml

Addresses issues described in #724 
*Stability*
*Code quality*
~- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~

Update github run_app_tests workflow

---

packages/rx_bloc/README.md

Add todo app link in the rx_bloc readme

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

Fixe last vesrion name in the change log
*Stability*
*Code quality*

Fixe last vesrion name in the change log

---

.github/workflows/build_and_test_rx_bloc_packages.yaml
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/run_app_tests.yaml

Update codeconv to the new version
*Stability*
*Code quality*

Update codecov to version 4

---

README.md

Codecov badge to be with the correct token
*Stability*
*Code quality*

Add codecov badge with token

---

.github/workflows/build_and_test_rx_bloc_packages.yaml
README.md
packages/flutter_rx_bloc/README.md
packages/rx_bloc/README.md
packages/rx_bloc_generator/README.md
packages/rx_bloc_list/README.md
packages/rx_bloc_test/README.md

> Closes: #412 
Fix the broken code coverage badges

#412 Fix the broken coverage

---

packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/bin/server/controllers/auth_matrix_controller.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/lib/lib_auth_matrix/extensions/exception_extensions.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/lib/lib_auth_matrix/methods/pin_biometric/di/auth_matrix_pin_biometrics_page_with_dependencies.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/lib/lib_auth_matrix/methods/pin_biometric/services/auth_matrix_pincode_service.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/lib/lib_auth_matrix/methods/pin_biometric/views/auth_matrix_pin_biometrics_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/views/create_pin_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/views/update_pin_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/views/verify_pin_code_page.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/extensions/error_model_extensions.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml

Upgrade from widget_toolkit_pin ^0.0.2 to ^0.1.0

Upgrade from widget_toolkit_pin ^0.0.2 to ^0.1.0

---

packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/bin/server/controllers/auth_matrix_controller.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/lib/lib_router/routes/auth_matrix_routes.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth_matrix/__brick__/test/lib_auth_matrix/services/auth_matrix_service_test.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/router.dart

Add unit tests to the AuthMatrixService

Add unit tests

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/README.md
packages/rx_bloc_cli/doc/golden_tests.md
packages/rx_bloc_cli/example/README.md
packages/rx_bloc_cli/example/docs/golden_tests.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/README.md
packages/rx_bloc_cli/pubspec.yaml

> Closes: 2
*Stability*
*Code quality*

Add link to golden tests smart widgets with di doc in the example docs.

---

.github/workflows/build_and_test_rx_bloc_packages.yaml
.github/workflows/test_rx_bloc_cli_project_generation.yaml
.github/workflows/test_rx_bloc_intellij_plugin.yml

Remove redundant ci triggers

---

packages/rx_bloc_cli/CHANGELOG.md

Fixes incorrect links in the `rx_bloc_cli` package CHANGELOG

Fix rx_bloc_cli CHANGELOG links

---

packages/rx_bloc_cli/example/README.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/README.md

> Closes: None
Addresses an issue with URLs in generated documentation mentioned [here](https://github.com/Prime-Holding/rx_bloc/pull/770#discussion_r1704954646).

Update urls to use full paths

---

packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/blocs/router_bloc.dart

Add workaround for GoRouter.pop issue on Flutter 3.24

---

packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/blocs/router_bloc.dart

Fix workaround for GoRouter.pop issue on Flutter 3.24

---

examples/todoapp/lib/feature_todo_list/views/todo_list_page.dart

Fix bug on todo_list_page

---

.github/workflows/build_rx_bloc_intellij_plugin.yml
extensions/intellij/intellij_generator_plugin/build.gradle

Fix broken intellij plugin pipeline

---

packages/rx_bloc_cli/example/docs/patrol_integration_test.md
packages/rx_bloc_cli/mason_templates/bricks/patrol_integration_tests/__brick__/docs/patrol_integration_test.md

Fix patrol documentation typos

---

packages/rx_bloc_cli/CHANGELOG.md

> Closes: None
Updates rx_bloc_cli changelog to include more information on what the changes are covering.

Update rx_bloc_cli changelog

---

examples/todoapp/ios/Podfile
examples/todoapp/ios/Podfile.lock
examples/todoapp/lib/base/common_mappers/error_mappers/dio_error_mapper.dart

Fix todoapp not compiling on iOS
*Stability*
*Code quality*

Fix todoapp not compiling on iOS

---

.github/CONTRIBUTING.md

> Closes: #495 
Introduces `CONTRIBUTING.md` file which describes how someone can contribute to the repository.

Add contributing file

---

packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/lib/l10n/network_lookup/counter_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_deeplink/__brick__/lib/l10n/network_lookup/deep_link_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_deeplink/__brick__/lib/l10n/network_lookup/enter_message_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_login/__brick__/lib/l10n/network_lookup/login_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_otp/__brick__/lib/l10n/network_lookup/otp_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_qr_scanner/__brick__/lib/l10n/network_lookup/qr_code_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_widget_toolkit/__brick__/lib/l10n/network_lookup/widget_toolkit_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_change_language/__brick__/lib/l10n/network_lookup/lib_change_language_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_dev_menu/__brick__/lib/l10n/network_lookup/lib_dev_menu_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_mfa/__brick__/lib/l10n/network_lookup/mfa_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/l10n/network_lookup/lib_pin_code_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/network_lookup/error_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/network_lookup/field_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/network_lookup/lib_router_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/network_lookup/notifications_lookup.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/network_lookup/profile_lookup.dart

Improve network lookup switch statement

---

examples/todoapp/integration_test/tests/add_todo_page_test.dart
examples/todoapp/integration_test/tests/edit_todo_page_test.dart
examples/todoapp/integration_test/tests/negative_add_todo_page_test.dart
examples/todoapp/integration_test/tests/statistics_page_test.dart
examples/todoapp/integration_test/tests/todo_details_page_test.dart
examples/todoapp/integration_test/tests/todo_list_test.dart
examples/todoapp/lib/feature_todo_list/blocs/todo_list_bloc.dart
examples/todoapp/pubspec.lock

This PR aims to fix the currently existing issue where integration tests on the todo app fail
Closes: #816 
*Stability*
*Code quality*

Shorten the descriptions of tests

---

examples/todoapp/bin/run_integration_tests.dart
examples/todoapp/bin/run_integration_tests.sh
examples/todoapp/integration_test/main/base/utils.dart
examples/todoapp/pubspec.lock
examples/todoapp/pubspec.yaml

> Closes: #816 
This PR implements new script for running integration tests into the todoapp, it also fixes two failing integration tests
*Stability*
*Code quality*

Implement new integration test script into todoapp, fix failing test

---

.github/workflows/golden_test_generation.yaml

Fix/Add rx_bloc_cli options to golden_test_generation.yaml

---

.github/workflows/build_and_test_rx_bloc_packages.yaml
.github/workflows/build_rx_bloc_intellij_plugin.yml
.github/workflows/fastlane_build_and_deploy_android_app.yaml
.github/workflows/fastlane_build_and_deploy_ios_app.yaml
.github/workflows/firestore-poc.yml
.github/workflows/golden_test_generation.yaml
.github/workflows/publish_flutter_rx_bloc.yaml
.github/workflows/publish_rx_bloc.yaml
.github/workflows/publish_rx_bloc_cli.yaml
.github/workflows/publish_rx_bloc_generator.yaml
.github/workflows/publish_rx_bloc_list.yaml
.github/workflows/publish_rx_bloc_test.yaml
.github/workflows/test_rx_bloc_cli_project_generation.yaml
.github/workflows/test_rx_bloc_intellij_plugin.yml
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/build_and_deploy_android_app.yaml
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/{{#cicd_github}}.github{{/cicd_github}}/workflows/build_and_deploy_ios_app.yaml

Chore/update GitHub workflow dependencies

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/feature_profile/views/profile_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/l10n/arb/feature_profile/bg.arb
packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/l10n/arb/feature_profile/en.arb
packages/rx_bloc_cli/mason_templates/bricks/feature_showcase/__brick__/lib/feature_showcase/views/showcase_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_change_language/__brick__/lib/l10n/arb/lib_change_language/bg.arb
packages/rx_bloc_cli/mason_templates/bricks/lib_change_language/__brick__/lib/l10n/arb/lib_change_language/en.arb
packages/rx_bloc_cli/mason_templates/bricks/lib_change_language/__brick__/lib/lib_change_language/ui_components/language_picker_button.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/l10n/arb/lib_pin_code/bg.arb
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/l10n/arb/lib_pin_code/en.arb
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/common_ui_components/app_divider.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/common_ui_components/app_list_tile.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/theme/design_system/design_system_icons.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/arb/feature_notifications/bg.arb
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/arb/feature_notifications/en.arb

> Closes: #868 
This PR implements a profile screen redesign
*Stability*
*Code quality*

Redesign profile screen

---

packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/feature_profile/views/profile_page.dart

Fix missing padding

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/processors/android/app_build_gradle_processor.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/feature_profile/views/profile_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_qr_scanner/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/pages/qr_scanner_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_qr_scanner/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/steps_utils/qr_scanner_steps.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_qr_scanner/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/tests/qr_scanner_test.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/pages/home_page.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/steps_utils/home_page_steps.dart

> Closes: #879 
This PR adds an integration test for qr scanner feature that uses native automation.
This PR also fixes a bug in the project generation process where android app build gradle wasn't properly set up
*Stability*
*Code quality*

Add test for qr scanner

---

packages/rx_bloc_cli/lib/src/commands/create_command.dart

> Closes: #840 
*Stability*
*Code quality*

Fix/CLI log for Remote Translations usage

---

packages/rx_bloc_cli/example/docs/feature_creation.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/docs/feature_creation.md

Add feature documentation

---

packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/test/feature_profile/blocs/profile_test.dart

This PR add's Profile page tests
*Stability*
*Code quality*

Add profile page tests

---

packages/rx_bloc_cli/mason_templates/bricks/lib_mfa/__brick__/lib/lib_mfa/methods/pin_biometric/services/mfa_pincode_service.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_mfa/__brick__/lib/lib_mfa/methods/pin_biometric/views/mfa_pin_biometrics_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/services/create_pin_code_service.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/services/verify_pin_code_service.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/views/verify_pin_code_page.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/blocs/create_pin_bloc_test.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/blocs/update_and_verify_pin_bloc_test.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/mock/update_pin_code_service_mock.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/mock/verify_pin_code_service_mock.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/services/create_pin_code_service_test.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/services/verify_pin_code_service_test.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/blocs/router_bloc.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_splash/blocs/splash_bloc.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml

> Closes: #909 
This PR implements all the necessary changes required by the newest version of widget_toolkit_pin
*Stability*
*Code quality*

Upgrade widget_toolkit_pin to 0.3.0

---

packages/rx_bloc_generator/CHANGELOG.md
packages/rx_bloc_generator/lib/rx_bloc_generator.dart
packages/rx_bloc_generator/lib/src/utilities/extensions.dart
packages/rx_bloc_generator/pubspec.yaml
packages/rx_bloc_generator/test/src/rx_bloc_test.dart

> Closes: #923
Update rx_bloc_generator dependencies to major versions
*Stability*
*Code quality*

Update rx_bloc_generator dependencies

---

packages/rx_bloc_cli/bin/compile_test_project.sh
packages/rx_bloc_cli/example/README.md
packages/rx_bloc_cli/lib/src/models/command_arguments/create_command_arguments.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_login/__brick__/lib/feature_login/ui_components/sign_up_button.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_login/__brick__/lib/feature_login/views/login_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/base/extensions/string_extensions.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/base/models/confirmed_credentials_model.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/base/models/user_role.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/README.md

Address some comments in the onboarding epic branch

Fix some comments

---

packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding_phone_confirmation/blocs/onboarding_phone_bloc.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding_phone_confirmation/ui_components/phone_number_form.dart

Fix/Onboarding - Step 2: Submit validation & showErrors

---

packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding_phone_confirmation/views/onboarding_phone_confirm_page.dart

| Screenshot 1 | Screenshot 2 |
| ------------ | ------------ |
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-12-27 at 22:07:31](https://github.com/user-attachments/assets/ee7b1c1a-594e-4a51-9538-f2def98eb4b6) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-12-27 at 22:07:48](https://github.com/user-attachments/assets/0933ce51-4ae9-4204-8410-413c3bb8a6dd) |
*Stability*

Fix the keyboard overlapping the text field

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/l10n/arb/bg.arb

Fix language modal translations

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/theme/design_system/design_system_icons.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_dashboard/services/dashboard_service.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_dashboard/views/dashboard_page.dart

#952
*Stability*
*Code quality*

Dashboard improvements

---

packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/fastlane/Fastfile

Make the fastlane compatible with the established project structure.

Make the fastlane compatible with the established project structure

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/mason_templates/bricks/lib_realtime_communication/__brick__/lib/base/data_sources/remote/sse_remote_data_source.dart

This pull request updates the SSE code to close the connection when the stream is closed.

Cancel the HTTP request for SSE when the stream is closed

---

packages/rx_bloc_cli/mason_templates/bricks/lib_auth/__brick__/lib/feature_profile/ui_components/logout_action_button.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth/__brick__/lib/lib_auth/blocs/user_account_bloc.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_auth/__brick__/test/base/common_blocs/user_account_bloc_mock.dart

>  #952 
*Stability*
*Code quality*

Logout button improvements - Add loading state on each logout

---

packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/feature_profile/blocs/profile_bloc.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/test/feature_profile/blocs/profile_test.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/common_services/push_notifications_service.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/repositories/push_notification_repository.dart

- Removed syncNotificationSettings method called on ProfilePage load
- Removed onError log of Firebase getToken method
*Stability*

Remove syncNotificationSettings on ProfilePage load

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_dashboard/views/dashboard_page.dart

Add an animation to the success widget of the dashboard page #967
*Stability*
*Code quality*

Add an animation to the success widget of the dashboard page

---

packages/rx_bloc_cli/lib/src/processors/ios/info_plist_processor.dart

Fix/iOS deeplinks Invalid URL

---

packages/rx_bloc_cli/example/README.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/README.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/bin/server/config.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/bin/server/controllers/push_notifications_controller.dart

> Closes: #908 
This PR adds necessary documentation for setting up local server

Update readme for notifications

---

packages/rx_bloc/CHANGELOG.md
packages/rx_bloc/lib/src/result_extensions.dart
packages/rx_bloc/pubspec.yaml

Fix static analysis issue with angle brackets interpreted as HTML

---

packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

Fix/Bump rxBlocCliPackageVersion

---

packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

Merge develop into master

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/processors/android/android_manifest_processor.dart
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/pubspec.yaml

Fix/RxBlocCli static analysis warning, add topics to pubspec

---

packages/rx_bloc_cli/lib/src/processors/android/android_main_activity_processor.dart
packages/rx_bloc_cli/lib/src/processors/android/android_manifest_processor.dart
packages/rx_bloc_cli/lib/src/processors/android/app_build_gradle_processor.dart
packages/rx_bloc_cli/lib/src/processors/android/settings_gradle_processor.dart
packages/rx_bloc_cli/lib/src/processors/common/generated_files_processor.dart
packages/rx_bloc_cli/lib/src/processors/ios/info_plist_processor.dart
packages/rx_bloc_cli/lib/src/processors/ios/podfile_processor.dart
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_flavor_config/__brick__/android/environments/development/google-services.json

Migrate gradle files to .kts

---

.gitignore
packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/lib/src/utils/flavor_generator.dart
packages/rx_bloc_cli/pubspec.yaml
packages/rx_bloc_generator/test/src/rx_bloc_test.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_behaviour_subject_no_seed.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_class_only.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_events_missing.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_events_no_fields.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_generic_bloc.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_long_state_method.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_seed_for_publish_subject_error.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_states_missing.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_states_no_body_definition.dart
packages/rx_bloc_generator/test/src/rx_bloc_test_states_no_methods.dart

This PR addresses an issue where the generated projects do not contain configured flavors.

Fix flavors in generated projects

---

.github/workflows/build_rx_bloc_intellij_plugin.yml

Add option for manually triggering the github action for intellij plugin

---

extensions/intellij/intellij_generator_plugin/CHANGELOG.md
extensions/intellij/intellij_generator_plugin/gradle.properties

Updated the intellij plugin changelog
