Prime-Holding/rx_bloc

examples/booking_app/ios/Runner.xcodeproj/project.pbxproj
examples/booking_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
examples/booking_app/lib/feature_hotel/search/ui_components/hotel_sort_page.dart
packages/rx_bloc/lib/src/result_extensions.dart
packages/rx_bloc/test/result_extensions_test.dart
packages/rx_bloc_list/lib/src/extensions/identifiable_extensions.dart

Change some comments. Change the name of two methods to avoid confusion with the other methods with the same names in the same file.

Add changes on comments and change the names of two method

---

packages/rx_bloc_list/lib/src/extensions/identifiable_extensions.dart

When making a ManageOperation.remove the method returns not a paginated list if the identifiable is not contained in Paginated List

Fix returns not a paginated list if the identifiable is not contained in Paginated List

---

packages/rx_bloc_generator/pubspec.yaml

Bump max analyzer version to 6.0.0
[issue 379](https://github.com/Prime-Holding/rx_bloc/issues/379)

bump analyzer version

---

packages/rx_bloc_cli/bin/compile_win.bat
packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/main/pages/counter_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/{{#enable_patrol}}integration_test{{/enable_patrol}}/tests/counter_test.dart
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/router.dart
packages/rx_bloc_cli/mason_templates/bricks/patrol_integration_tests/__brick__/android/app/src/androidTest/java/{{domain_name}}/{{organization_name}}/{{project_name}}/MainActivityTest.java
packages/rx_bloc_cli/mason_templates/bricks/patrol_integration_tests/__brick__/integration_test/main/configuration/config_params.dart
packages/rx_bloc_cli/mason_templates/bricks/patrol_integration_tests/__brick__/integration_test/main/configuration/patrol_base_config.dart
packages/rx_bloc_cli/mason_templates/bricks/patrol_integration_tests/__brick__/ios/RunnerUITests/RunnerUITests.m
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/.gitignore
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/app/build.gradle
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/build.gradle
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/gradle/wrapper/gradle-wrapper.properties
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_home/views/home_page.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
packages/rx_bloc_cli/pubspec.yaml

Close: #540 
This pull request aims to update the dependencies in the rx_bloc_cli project as well as dependencies within the bricks to their latest versions.
Since counter integration test was made before implementing otp feature, the current counter integration test will fail if otp feature is enabled, and since otp feature is depending on [pinput package ](https://pub.dev/packages/pinput) currently there isn't a way of testing this feature.
Until this issue is solved I left a TODO to mark that there is a missing step in the counter test process

Update bloc cli dependencies

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/android/build.gradle

Close: #538 
Kotlin version for rx_bloc_cli updated to `1.9.0`

Kotlin version updated

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/app/{{project_name}}.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_profile/views/profile_page.dart
packages/rx_bloc_cli/pubspec.yaml

This PR should fix issues with the generated project being created with some parts of disabled bricks.
The issue occurred when the project was generated with the interactive flag enabled, and using all the default values.

Fix generated project being created with parts of disabled bricks

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/mason_templates/bricks/lib_router/__brick__/lib/lib_router/router.dart

> Closes: #601 
Addresses issue where OTP screen is not opened on login
~~UI checked in Light / Dark mode~~
*Stability*
~~Added unit tests for new code and verified existing tests work as expected~~
*Code quality*
~~If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~~

Update redirects to handle case where OTP screen is not opened on login

---

.github/workflows/test_rx_bloc_cli_project_generation.yaml
packages/rx_bloc_cli/bin/compile.sh
packages/rx_bloc_cli/bin/generate_test_project.sh
packages/rx_bloc_cli/mason_templates/README.md

Add github workflow for generating rx_bloc_cli projects with different flags
> Closes: #610 
This PR adds a github workflow which generates rx_bloc_cli test project with different configurations (default project generation, all flags enabled, all flags disabled, without showcase features). This allows for easier error checking when adding new or updating existing features/code.
*Stability*
*Code quality*
~- [] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`~
~- [ ] If an unrelated part of the codebase …

Add github workflow for generating rx_bloc_cli projects

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/rx_bloc_cli_constants.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/fastlane/Fastfile
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/fastlane/README.md
packages/rx_bloc_cli/pubspec.yaml

This PR updates the build_custom fastlane task so that if the environment variables do not exist the user will be prompted to enter their values.
*Stability*
*Code quality*

Add a fastlane task to prompt the user for envronment variables

---

packages/flutter_rx_bloc/CHANGELOG.md
packages/flutter_rx_bloc/lib/src/rx_text_form_field_builder.dart
packages/flutter_rx_bloc/pubspec.yaml

This PR should fix the padding of the suffix icon of RxTextFormFieldBuilder.
The bug occurs when the RxTextFormFieldBuilder is used with the TextField or TextFormField that has a specified height of under 50 pixels. 
Screenshots of before and after are included ⬇️ 
*Stability*
*Code quality*

Remove RxTextFormFieldBuilder suffix icon padding

---

packages/rx_bloc_generator/CHANGELOG.md
packages/rx_bloc_generator/lib/src/builders/state_field.dart
packages/rx_bloc_generator/lib/src/builders/state_getter_method.dart
packages/rx_bloc_generator/lib/src/builders/state_method.dart
packages/rx_bloc_generator/lib/src/utilities/extensions.dart
packages/rx_bloc_generator/pubspec.yaml

Fix compiling issue caused by the analyzer version 6.5.0
*Stability*
*Code quality*

Update dependencies and bump analyzer constraints to ^6.5.0

---

examples/todoapp/lib/base/models/todo_model.dart

Todo app wasn't able to update todos and was creating new one instead.
When creating or updating a todo the description input wasn't taken into account.

Fixed bug in update and create of todo

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/example/docs/continuous_delivery.md
packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/fastlane/Fastfile

> Closes: #725
This build introduces a change to Fastfile which removes any credentials files after a build/deployment has completed.
*Stability*
*Code quality*
~- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~

Update fastfile to remove credentials post build/deploy

---

packages/rx_bloc_cli/bin/compile_test_project.sh

This PR includes a small enhancement for the `compile_test_project` script which automatically replaces specific content for the generated example project in order faster and more consistent updates to the documentation.

Add content replacement for example project

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/processors/android/app_build_gradle_processor.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml

Fixes an issue where rx_bloc_cli generated projects cannot be built on android.

Update flutter local notifications dependency

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/commands/create_command.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_showcase/__brick__/lib/l10n/network_lookup/showcase_lookup.dart

Fix generated project error when generated with a name different than testapp
> Closes: #838 
This PR fixes an issue where the generated project was being generated with an error due to showcase brick. It also introduces a new dart command in the project generation process, that aims to primarily organize imports 
This issue is not related to the issue mentioned in the ticket description but was introduced with the implementation of showcase brick.
As for the:
After investigating the bricks used to generate new projects, there is no mention of the file  `update_button_golden_test.dart`. Although when I initially generated a new project there was an error, after deleting all the bundles from the `rx_bloc_cli/lib/src/templates`, and regenerating them using the …

Fix generated project error when generated with name different than testapp

---

packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_splash/blocs/splash_bloc.dart

> Closes: #917 
The pin code page should show only when pincode is not null.
There was small mistake in the splash screen that was showing the pin code page when there was no pin code set.
*Stability*
*Code quality*

Pincode verification page should show only when there's pincode

---

packages/rx_bloc_cli/CHANGELOG.md
packages/rx_bloc_cli/lib/src/processors/ios/podfile_processor.dart

> Closes: #921 
This PR fixes the QR scanner feature not asking for camera permission on iOS devices
*Stability*
*Code quality*

Fix qr scanner camera permission

---

packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding/ui_components/register_form.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding/views/onboarding_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding_email_confirmation/views/onboarding_email_confirmation_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/feature_onboarding_email_confirmation/views/onboarding_email_confirmed_page.dart
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/l10n/arb/feature_onboarding/bg.arb
packages/rx_bloc_cli/mason_templates/bricks/feature_onboarding/__brick__/lib/l10n/arb/feature_onboarding/en.arb
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/theme/design_system/design_system_typography.dart

- Text changes
- Remove the feature-specific code from the design system
- Remove the text widgets from the register form
- Apply consistent layout and colors across the onboarding flow
- Fix form-related issues on small devices sizes such as iPhone SE
*Stability*
| Screenshot 1 | Screenshot 2 | Screenshot 3 |
|--------------|--------------|--------------|
| ![Simulator Screenshot - iPhone 16 Pro Max - 2024-12-26 at 16 07 08](https://github.com/user-attachments/assets/9db632bd-5243-4bba-9c6e-583b94590e9d) | ![Simulator Screenshot - iPhone 16 Pro Max - 2024-12-26 at 16 07 19](https://github.com/user-attachments/assets/dc9bf99f-064d-4bb7-8378-6e0f3b64ba81) | ![Simulator Screenshot - iPhone 16 Pro Max - 2024-12-26 at 16 07 …

Improve the onboarding flow (register/email confirmation)

---

packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/fastlane/Fastfile

Addresses Fastlane issue where Android build would fail due to incorrect path (assumes specific mono-repo structure).

Fix fastfile invalid path issue on android

---

packages/rx_bloc_cli/lib/src/extensions/string_buffer_extensions.dart
packages/rx_bloc_cli/lib/src/processors/ios/info_plist_processor.dart

On biometrics toggle click in the profile page the app was crashing on physical iOS devices.
The problem was that the camera and biometric descriptions were added in the wrong place in the `Info.plist` file. The change in the plist processor was needed.
*Stability*
*Code quality*

Fix crash on biometrics switch on iOS physical device

---

packages/rx_bloc_cli/example/README.md
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/app/initialization/firebase_messaging_callbacks.dart
packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/utils/local_notifications.dart

> Closes: #925 
This PR fixes a bug where local notifications weren't displayed on an android device. It also conditionally displays the notification based on user settings controlled from the profile page.
*Stability*
*Code quality*
~- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`~
~- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes~

Fix local notification not being shown on android
